### ISSUE TITLE
autoplugin bad argument #1 to 'lines' (ux0:tai/config.txt: Is a directory)

### ISSUE THREAD

**Issue by rakuen07** [theheroGAC/Autoplugin#27] opened 2018-08-09 14:08 UTC
successfully installed sd2vita as ux0. but autoplugin does not show plugins to install. how to fix this? thank you
![2018-08-09-150718](https://user-images.githubusercontent.com/40835691/43904229-be383f0a-9c20-11e8-92db-e9414d21863c.jpg)

**Comment by NeonLightning** [comment] 2018-08-09 14:17
#26

**Comment by theheroGAC** [comment] 2018-08-09 16:46
autoplugin is currently not compatible with tf-card-plugin-tool

**Comment by ONElua** [comment] 2018-08-10 14:09
please send me capture!!!!
then TF card creates a completed folder ux0:tai/config.txt ??

**Comment by NeonLightning** [comment] 2018-08-10 16:35
what capture do you need?

**Comment by chchris25** [comment] 2018-08-26 12:33
I figured out the problem. Delete the tai folder in ux0 if you already have it installed in ur0

**Comment by chchris25** [comment] 2018-09-02 13:51
Everytime you update it recreates the ux0:tai/config.txt directory. You must delete it on every update to get Autoplugin working.

**Comment by redion1992** [comment] 2018-09-07 17:42
I also have this error, though it’s a known thing for me. I have config.txt as a directory on ux0:, since I only modify plugins on ur0:, I use that trick to ensure that there is no file created to override my plugins list. If this is the case, it may be better to warn the user that plugin configuration on ux0: is disabled, without crashing the app.

**Comment by EduardAlan** [comment] 2018-09-22 19:11
I was able to fix the autoplugin ur0: tai error by copying everything to
the ux0: tai folder

**Comment by EduardAlan** [comment] 2018-09-22 19:14
I copied everything inside the url: tai folder into ux0: tai so it

**Comment by xiuyanLi** [comment] 2018-12-03 14:09
function fileExist(file)

	if io.open(file, "r") then
			return true
	end
	
	return false
 
end

function directoryExist(file)

	if files.list(file) then
			return true
	end
	
	return false
 
end


This maybe fix this bug.

**Comment by theheroGAC** [comment] 2018-12-03 15:06
Test now.Thank you

**Comment by bamhm182** [comment] 2019-01-23 12:17
This issue still remains. We could solve it with a files.info(path).directory check in script.lua and telling the user to uninstall tf card and year StorageMgr instead. Not an ideal fix, but could be a start.

**Comment by bamhm182** [comment] 2019-01-24 01:48
I have confirmed this problem to be fixed on both my PS Vita and PSTV. Can we close it?

**Comment by asakapa619** [comment] 2019-02-16 07:40
This is my 1st time using this plugin after running the app it always prompting "creating Config_backup.txt" and does not show plugins to install. how to fix this? thanks
![img20190216153214](https://user-images.githubusercontent.com/47685889/52896274-6658df80-3200-11e9-9c17-76826dd3b221.jpg)

**Closed** 2019-04-16 03:50 UTC
Labels: enhancement
