### ISSUE TITLE
Q-encore

### ISSUE THREAD

**Issue by gered13** [theheroGAC/Autoplugin#100] opened 2018-12-29 10:32 UTC
Doesn't work on my vita slim. H-encore on my sd2vita ux0. Booted without the q-encore thing﻿

**Comment by theheroGAC** [comment] 2018-12-29 18:55
copy and past original q-encore memorycard->sd2vita

**Comment by bamhm182** [comment] 2019-01-04 23:41
You should still have access to the primary storage, just under a mount point other than ux0. It would be very interesting to see Autoplugin check common mount points for h-encore q-encore and patch them in all locations.

**Comment by bamhm182** [comment] 2019-01-08 23:33
I created a new Pull Request to fix this by checking uma0, ur0, and ux0 for H-Encore.

**Comment by theheroGAC** [comment] 2019-01-11 14:57
new autoplugin available https://github.com/theheroGAC/Autoplugin/releases/download/3.67/Autoplugin.vpk

**Comment by theheroGAC** [comment] 2019-01-11 15:39
Ok wait your test :)

**Comment by bamhm182** [comment] 2019-01-11 19:50
I don't know how, but it looks like I screwed this up. I wiped my system and reinstalled h-encore. Using Autoplugin to install Q-Encore breaks H-Encore. I'll fix this tonight.

**Comment by theheroGAC** [comment] 2019-01-11 19:58
look here https://github.com/theheroGAC/Autoplugin/commit/e39770a1d730b88bc5089d18cd2f3bb0a0a11634
Q-encore use kernel and users from vitashell

**Comment by bamhm182** [comment] 2019-01-11 20:35
From my phone, I don't see anything that would have changed to break it. When I get home, I'll see if I can find something.

I didn't change commons.lua as far as loading the user and kernel go. The only thing I can think of is that something is screwed up with the function in qencore.lua.

**Comment by theheroGAC** [comment] 2019-01-12 07:43
Autoplugin v3.68 available

**Comment by bamhm182** [comment] 2019-01-12 14:41
I downloaded 3.68 and tested it. The new code works as intended. I opened an issue on VitaShell about not being able to copy into decrypted folders on mount points other than ux0, TheOfficialFloW agreed that it doesn't work and closed the ticket. It sounds like the best we're going to be able to do is check if the user is using SD2VITA and ask them to not for a moment.

**Comment by ONElua** [comment] 2019-01-14 20:20
> Bug?I have already installed qencore manually.（ux0 and uma0）
> When I try to use the new version of autoplugin to install it again,after reboot,click on the lock bubble,the game bittersmile starts.
> I am not sure if this is an accidental problem. My location is already 11 o'clock at night. Plan to try again tomorrow.
> 
> Edit:
> Tried again.Not working.Only ux0 works well. Just like the test results of bamhm182.
> By the way,if everyone installed the h-encore bubble both in ux0 and uma0,after installing qencore in ux0,just copy the savedata folder of h-encore from ux0 to uma0,decryption is not required.Maybe it's okay to let Autoplugin do these copy and paste operations.

Can you help me try again? To send you the FIX

**Comment by yexun1995** [comment] 2019-01-15 11:40
> > Bug?I have already installed qencore manually.（ux0 and uma0）
> > When I try to use the new version of autoplugin to install it again,after reboot,click on the lock bubble,the game bittersmile starts.
> > I am not sure if this is an accidental problem. My location is already 11 o'clock at night. Plan to try again tomorrow.
> > Edit:
> > Tried again.Not working.Only ux0 works well. Just like the test results of bamhm182.
> > By the way,if everyone installed the h-encore bubble both in ux0 and uma0,after installing qencore in ux0,just copy the savedata folder of h-encore from ux0 to uma0,decryption is not required.Maybe it's okay to let Autoplugin do these copy and paste operations.
> 
> Can you help me try again? To send you the FIX

Ok.I am free at noon tomorrow. If you are not in a hurry, you can send it to me.

**Comment by ONElua** [comment] 2019-01-15 15:05
> That's a very interesting find. I imagine we would have no problem copying the folder from ux0 to other places. I'll play around with it and see what I can come up with when I get some time.

The functions mount worked correctly, the problem was to modify/write inside the mounted route, only in ux0 can be achieved.
And it really is based on your idea of mount more partitions

**Comment by bamhm182** [comment] 2019-01-19 15:04
This issue appears to have been resolved. Can we close it?

**Closed** 2019-01-31 18:39 UTC
